# Generated by Django 6.0.7 on 2026-07-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='curator_rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
