# Generated by Django 6.0.7 on 2026-07-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_anime_curator_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='animerating',
            name='rating_rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
