# Generated by Django 6.0.7 on 2026-09-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_anime_rating_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='jikan_synced',
            field=models.BooleanField(default=False),
        ),
    ]
